gitRepo:
  gitProvider: my_github
  path: jfrog/jfrog-pipelines-helm-blue-green-sample
  branch: main

appImage:
  registry: my_artifactory
  registryUrl: myartifactory.myorg.com

appChart:
  sourceArtifactory: my_artifactory

runtime:
  k8s_integration: my_k8s
  namespace: namespace
  blueReleaseName: app-blue
  greenReleaseName: app-green
  idleServiceName: app-idle
  liveServiceName: app


