gitRepo:
  #gitProvider: rajGit                             # <-- replace with your GitRepo integration name
  gitProvider: myGithub
  path: RjSH1/jfrog-pipelines-helm-blue-green-sample  # <-- replace jfrog with your username or org name
  branch: main

appImage:
  #registry: rajArt                            # <-- replace with your Artifactory integration name
  registry: myArtifactory
  #registryUrl: myartifactory.myorg.com                # <-- replace with the url to your Artifactory environment
  #registryUrl: demo.jfrog-pipelines.com
  registryUrl: newenv25.jfrogdev.org

appChart:
  sourceArtifactory: myArtifactory                   # <-- replace with your Artifactory integration name

runtime:
  k8s_integration: s_kubernetes                            # <-- replace with your Kubernetes integration name
  #namespace: namespace                                # <-- replace with the name of the Kubernetes namespace where the Helm chart will be deployed
  namespace: pipe-master-pool
  blueReleaseName: app-blue
  greenReleaseName: app-green
  idleServiceName: app-idle
  liveServiceName: app


